In [9]:
import numpy  as np


In [10]:
np.__version__

'1.23.1'

In [33]:
# array
# Scaler / 0-D array
a = np.array(50)
print(a)

50


In [29]:
print(a.shape) # shape of array

()


In [30]:
np.ndim(a) # dimension of array

0

In [34]:
# vector / 1-D array

b = np.array([10,20,30])
print(b)
print(b.shape)
print(np.ndim(b))

[10 20 30]
(3,)
1


In [36]:
# matrix / 2-D array
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(c.shape)
print(np.ndim(c))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [41]:
# tensor / 3-D array
c = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(c)
print(c.shape)
print(np.ndim(c))

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
(2, 2, 4)
3


In [45]:
print(type(a),type(b),type(c))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [46]:
type(b[2])

numpy.int32

In [47]:
a = np.array([1,2,3,4],dtype='int8')

In [48]:
a.dtype

dtype('int8')

In [49]:
type(a[0])

numpy.int8

In [52]:
arr = np.arange(8,dtype='int16')
print(arr)

[0 1 2 3 4 5 6 7]


In [53]:
arr.dtype

dtype('int16')

In [56]:
arr = np.arange(1,10,2)#stat,stop,step
print(arr)

[1 3 5 7 9]


In [65]:
mat = np.identity(3,dtype='int8')
mat2= np.eye(3)


In [66]:
print(mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [67]:
print(mat2)on

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
