In [1]:
import numpy as np

In [63]:
arr = np.random.randint(10,100,(10,2))
arr

array([[54, 43],
       [93, 91],
       [22, 44],
       [84, 80],
       [16, 39],
       [87, 74],
       [53, 61],
       [88, 33],
       [56, 98],
       [24, 75]])

## Attributes of Numpy array

In [64]:
# shape
print(np.shape(arr))
print(arr.shape)

(10, 2)
(10, 2)


In [65]:
# dimension
print(np.ndim(arr))
print(arr.ndim)

2
2


In [66]:
# size 
# total elements in array
print(arr.size)

20


In [75]:
arr.dtype

dtype('int32')

In [76]:
arr.dtype = 'int8'

In [77]:
print(arr.dtype) 

int8


In [78]:
arr.dtype = 'float32'
arr

array([[7.57e-44, 6.03e-44],
       [1.30e-43, 1.28e-43],
       [3.08e-44, 6.17e-44],
       [1.18e-43, 1.12e-43],
       [2.24e-44, 5.47e-44],
       [1.22e-43, 1.04e-43],
       [7.43e-44, 8.55e-44],
       [1.23e-43, 4.62e-44],
       [7.85e-44, 1.37e-43],
       [3.36e-44, 1.05e-43]], dtype=float32)

In [79]:
arr.dtype

dtype('float32')

In [95]:
arr.dtype ='int8'
print(arr.dtype, "bits")
print(arr.itemsize,"bytes")

int8 bits
1 bytes


In [96]:
arr

array([[54,  0,  0,  0, 43,  0,  0,  0],
       [93,  0,  0,  0, 91,  0,  0,  0],
       [22,  0,  0,  0, 44,  0,  0,  0],
       [84,  0,  0,  0, 80,  0,  0,  0],
       [16,  0,  0,  0, 39,  0,  0,  0],
       [87,  0,  0,  0, 74,  0,  0,  0],
       [53,  0,  0,  0, 61,  0,  0,  0],
       [88,  0,  0,  0, 33,  0,  0,  0],
       [56,  0,  0,  0, 98,  0,  0,  0],
       [24,  0,  0,  0, 75,  0,  0,  0]], dtype=int8)

In [97]:
arr.dtype='int32'
arr

array([[54, 43],
       [93, 91],
       [22, 44],
       [84, 80],
       [16, 39],
       [87, 74],
       [53, 61],
       [88, 33],
       [56, 98],
       [24, 75]])

In [98]:
print(arr.itemsize,"bytes")

4 bytes


In [104]:
arr= np.array([1,2,3],np.int8)

In [105]:
arr.dtype

dtype('int8')

In [106]:
np.int16(arr)

array([1, 2, 3], dtype=int16)

### indexing of arrays

In [111]:
arr = np.random.randint(10,50,10)
print(arr)

[26 22 34 10 13 21 13 24 32 13]


In [113]:
arr2 = np.random.randint(10,50,(2,5))
print(arr2)

[[38 38 15 34 39]
 [19 16 33 38 30]]


In [119]:
arr2[1,2]=100
arr2

array([[ 38,  38,  15,  34,  39],
       [ 19,  16, 100,  38,  30]])

In [120]:
print(arr[0:4])

[26 22 34 10]


In [126]:
newArr = arr2[:2,2:4]

In [127]:
newArr

array([[ 15,  34],
       [100,  38]])

In [128]:
arr2[:2,:2]

array([[38, 38],
       [19, 16]])

In [132]:
arr2[:2,1:3]

array([[ 38,  15],
       [ 16, 100]])

In [139]:
arr3 = np.random.randint(1,10,(2,2,4))

In [140]:
arr3.ndim

3

In [141]:
arr3

array([[[3, 5, 9, 7],
        [8, 8, 3, 3]],

       [[3, 3, 1, 1],
        [8, 5, 1, 2]]])

In [209]:
arr3 =np.array([[[1,2,3,4],[0,0,0,0]],[[0,0,0,0],[0,0,0,0]]])

In [210]:
arr3

array([[[1, 2, 3, 4],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [211]:
arr3.ndim

3

In [212]:
# task-1
arr3[0,1,3]=50

In [213]:
arr3

array([[[ 1,  2,  3,  4],
        [ 0,  0,  0, 50]],

       [[ 0,  0,  0,  0],
        [ 0,  0,  0,  0]]])

In [214]:
arr3[1,1,1]=1
arr3[1,1,3]=1

In [215]:
arr3

array([[[ 1,  2,  3,  4],
        [ 0,  0,  0, 50]],

       [[ 0,  0,  0,  0],
        [ 0,  1,  0,  1]]])

In [260]:
newArr=arr3[0,:2,2:]
newArr = list(newArr)

In [261]:
l1 =[1,1]

In [264]:
newArr2 = np.array([[newArr],[l1]])

C:\Users\RAHUL SUTHAR\AppData\Local\Temp\ipykernel_2652\2300095197.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  newArr2 = np.array([[newArr],[l1]])


In [265]:
newArr2.ndim

3

In [269]:
# view of array

In [272]:
arr = np.random.randint(1,5,(2,5))

In [273]:
arr

array([[4, 3, 3, 3, 2],
       [1, 2, 2, 4, 3]])

In [274]:
view_Arr=arr[:2,:2]

In [275]:
view_Arr


array([[4, 3],
       [1, 2]])

In [279]:
view_Arr[0,0] = 5
# original array also change

In [280]:
view_Arr

array([[5, 3],
       [1, 2]])

In [281]:
arr

array([[5, 3, 3, 3, 2],
       [1, 2, 2, 4, 3]])

In [282]:
# copy view

In [284]:
copy_view = arr[:2,:2].copy()

In [287]:
copy_view[1,1]=10
#original array not change
copy_view

array([[ 5,  3],
       [ 1, 10]])

In [288]:
arr

array([[5, 3, 3, 3, 2],
       [1, 2, 2, 4, 3]])