In [3]:
import numpy as np


In [5]:
arr1=np.arange(1,5)
arr2 = np.arange(6,10)
print(arr1,arr2)

[1 2 3 4] [6 7 8 9]


In [11]:
# concatenate array
concatArr = np.concatenate((arr1,arr2))
print(concatArr)

[1 2 3 4 6 7 8 9]


In [14]:
mat1 = np.random.randint(0,10,size=(2,3))
mat2 = np.random.randint(10,20,size=(2,3))
print(mat1)
print(mat2)

[[2 3 5]
 [0 7 6]]
[[14 16 13]
 [17 14 13]]


In [18]:
concatMat = np.concatenate((mat1,mat2)
print(concatMat)
                          

[[ 2  3  5]
 [ 0  7  6]
 [14 16 13]
 [17 14 13]]


In [24]:
concatMat2= np.concatenate((mat1,mat2),axis=1)# default axis is 0
print(concatMat2)

[[ 2  3  5 14 16 13]
 [ 0  7  6 17 14 13]]


In [26]:
concatMat3= np.concatenate((mat2,mat1),axis=1)# default axis is 0
print(concatMat3)

[[14 16 13  2  3  5]
 [17 14 13  0  7  6]]


In [27]:
print(np.hstack((mat1,mat2)))

[[ 2  3  5 14 16 13]
 [ 0  7  6 17 14 13]]


In [38]:
t1 = np.random.randint(0,10,size=(2,2,3))
t2 = np.random.randint(10,20,size=(2,2,3))
print(t1)
print()
print(t2)

[[[9 0 2]
  [4 7 5]]

 [[2 4 2]
  [7 0 9]]]

[[[12 17 10]
  [15 13 17]]

 [[17 12 17]
  [14 14 16]]]


In [39]:
# axis-0 join
ans = np.concatenate((t1,t2),axis=0)
print(ans)

[[[ 9  0  2]
  [ 4  7  5]]

 [[ 2  4  2]
  [ 7  0  9]]

 [[12 17 10]
  [15 13 17]]

 [[17 12 17]
  [14 14 16]]]


In [40]:
# axis-1 join
ans2 = np.concatenate((t1,t2),axis=1)
print(ans2)

[[[ 9  0  2]
  [ 4  7  5]
  [12 17 10]
  [15 13 17]]

 [[ 2  4  2]
  [ 7  0  9]
  [17 12 17]
  [14 14 16]]]


In [41]:
#axis-2 join
ans3 = np.concatenate((t1,t2),axis=2)
print(ans3)

[[[ 9  0  2 12 17 10]
  [ 4  7  5 15 13 17]]

 [[ 2  4  2 17 12 17]
  [ 7  0  9 14 14 16]]]


In [78]:
#In concatenate shape of array should same 
# so we hstack and vstack numpy function 
arr3 = np.arange(1,5)
arr4  = np.random.randint(1,10,size=(2,4))


In [79]:
print(np.concatenate((arr3,arr4)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [80]:
np.vstack([arr3,arr4])

array([[1, 2, 3, 4],
       [3, 6, 9, 6],
       [2, 5, 6, 8]])

In [81]:
np.hstack([arr3,arr4])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [82]:
arr4


array([[3, 6, 9, 6],
       [2, 5, 6, 8]])

In [83]:
arr3

array([1, 2, 3, 4])

In [84]:
arr3=arr3.reshape((4,1))

In [87]:
arr4=arr4.reshape((4,2))

In [88]:
np.hstack([arr3,arr4])

array([[1, 3, 6],
       [2, 9, 6],
       [3, 2, 5],
       [4, 6, 8]])

In [98]:
arr5 =np.array([np.arange(1,7),np.arange(5,11)])
print(arr5.shape)
print(arr5)

(2, 6)
[[ 1  2  3  4  5  6]
 [ 5  6  7  8  9 10]]


In [100]:
# reshape
arr5 = np.reshape(arr5,(6,2))
arr5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [101]:
arr5 = arr5.reshape((4,3))
print(arr5)

[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]


### Question
Normalize the marks of students

### curving
1. center =user define
2. avg 
3. change = center-avg
4. normalize marks =  marks[i]+ change
     also clip the value so noone marks can exceed limit

In [162]:
marks_Student = np.array([32,50,48,29,80,56,90])
avg = np.average(marks_Student)
center = 75
change  = center-avg
marks_Student= np.add(marks_Student,change)
marks_Student= np.clip(marks_Student,0,100).astype('int32')
print(marks_Student)

[ 52  70  68  49 100  76 100]
