In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression
from  sklearn.metrics import r2_score

In [17]:
df = pd.read_csv("IceCreamData.csv")
df

Temperature     Revenue
0      24.566884  534.799028
1      26.005191  625.190122
2      27.790554  660.632289
3      20.595335  487.706960
4      11.503498  316.240194
..           ...         ...
495    22.274899  524.746364
496    32.893092  755.818399
497    12.588157  306.090719
498    22.362402  566.217304
499    28.957736  655.660388

[500 rows x 2 columns]

In [3]:
X = df.drop('Revenue',axis=1)
y = df['Revenue']

In [4]:
X

Temperature
0      24.566884
1      26.005191
2      27.790554
3      20.595335
4      11.503498
..           ...
495    22.274899
496    32.893092
497    12.588157
498    22.362402
499    28.957736

[500 rows x 1 columns]

In [5]:
y

0      534.799028
1      625.190122
2      660.632289
3      487.706960
4      316.240194
          ...    
495    524.746364
496    755.818399
497    306.090719
498    566.217304
499    655.660388
Name: Revenue, Length: 500, dtype: float64

In [6]:
reg = LinearRegression()

In [7]:
reg.fit(X,y)

LinearRegression()

In [8]:
reg.predict([[24]])

C:\Users\RAHUL SUTHAR\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([559.47827935])

In [9]:
reg.score(X,y)

0.979707200117581

In [10]:
m=reg.coef_


In [11]:
c =reg.intercept_

In [12]:
reg.predict([[24]])

C:\Users\RAHUL SUTHAR\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([559.47827935])

In [13]:
y = m*24+c
y

array([559.47827935])

In [23]:
x1 =((df['Revenue']-(m*df['Temperature']+c))**2).sum()
x2 =((df['Revenue']-df['Revenue'].mean())**2).sum()
1-(x1/x2)

0.979707200117581

In [19]:
df['predicated']  = m*df['Temperature']+c
df['E1'] =( df['Revenue']-df['predicated'])**2
df['E2'] =(df['Revenue']-df['Revenue'].mean())**2
df

Temperature     Revenue  predicated           E1            E2
0      24.566884  534.799028  571.634337  1356.839927    174.986643
1      26.005191  625.190122  602.476847   515.892818  10736.968619
2      27.790554  660.632289  640.761497   394.848358  19338.104150
3      20.595335  487.706960  486.469919     1.530271   1146.758061
4      11.503498  316.240194  291.507963   611.683292  42160.648024
..           ...         ...         ...          ...           ...
495    22.274899  524.746364  522.485865     5.109857     10.084357
496    32.893092  755.818399  750.178416    31.809403  54871.948417
497    12.588157  306.090719  314.766991    75.277691  46431.655306
498    22.362402  566.217304  524.362249  1751.845610   1993.312383
499    28.957736  655.660388  665.790120   102.611480  17980.023834

[500 rows x 5 columns]

In [20]:
R2 = 1 -(df['E1'].sum()/df['E2'].sum())

In [21]:
R2

0.979707200117581

In [ ]:
df = pd.read_csv("homeprices.csv")

In [ ]:
df

In [ ]:
plt.scatter(df['area'],df['price'],color='r')
m, c = np.polyfit(df.area,df.price, 1)
plt.plot(df.area, m*df.area+c)
plt.xlabel("Area")
plt.ylabel("price")
plt.show()

In [ ]:
new_df = df.drop("price",axis=1)
new_df


In [ ]:
price = df.drop("area",axis=1)
price

In [ ]:
reg  = LinearRegression()

In [ ]:
reg.fit(new_df,price)

In [ ]:
reg.predict([[4800]])

In [ ]:
reg.coef_

In [ ]:
reg.intercept_

In [ ]:
plt.scatter(df['area'],df['price'],color='r')
plt.plot(df.area,reg.predict(df[['area']]),color='b')